grails-app/domain/com/jpcf/backend/domain/Podcast.groovy
package com.jpcf.backend.domain

class Podcast {
    String name = ""
    String description = ""
    String fileName
    Date dateCreated

    static constraints = {
        name nullable: true
        description nullable: true
        fileName nullable: true
    }
}

grails-app/controllers/com/jpcf/backend/domain/FileUploadController.groovy
package com.jpcf.backend.domain

import grails.converters.JSON

class FileUploadController {
    static transactional = true
    def allowedMethods = []
    
    def SlideShowImageService
    
    def uploadPodcast = {
        println "IN upload()"
        def podcast
        
        def f = request.getFile('podcastUpload')
        if(!f.empty) {
            podcast = new Podcast()
            
            def filename = f.getOriginalFilename()
            def extension = filename[filename.lastIndexOf(".")..filename.size() - 1]
            
            podcast.save()
            
            def path = grailsApplication.config.podcasts.location.toString() + "/podcast" + podcast.id + extension

            podcast.fileName = path
			podcast.name = params.name
			podcast.description = params.description
            podcast.save()
            
            println "FILE: " + path
            
            new File(grailsApplication.config.podcasts.location.toString()).mkdirs()
            f.transferTo(new File(path))
        }    
        else {
            flash.message = 'File cannot be empty!'
            redirect(controller: "configuration", action: "index")
            return
        }
        
        redirect(controller: "configuration", action: "index")
    }

    def uploadImage = {
        println "IN upload()"
        
        def f = request.getFile('imageUpload')
        if(!f.empty) {
            def image = new SlideShowImage(orderIndex: SlideShowImageService.getNextOrderIndex())
            
            def filename = f.getOriginalFilename()
            def extension = filename[filename.lastIndexOf(".")..filename.size() - 1]
            
            image.save()
            
            def path = grailsApplication.config.images.location.toString() + "/image" + image.id + extension

            image.fileName = path
			image.text = params.text ?: ""
            image.save()
            
            println "FILE: " + path
            
            new File(grailsApplication.config.images.location.toString()).mkdirs()
            f.transferTo(new File(path))
        }    
        else {
            flash.message = 'File cannot be empty!'
        }
        
        redirect(controller: "configuration", action: "index")
    }
}

grails-app/controllers/com/jpcf/backend/domain/PodcastController.groovy
package com.jpcf.backend.domain

import org.springframework.dao.DataIntegrityViolationException
import grails.converters.JSON

class PodcastController {

    static allowedMethods = [save: "POST", update: "POST"]

    def create() {
        [podcastInstance: new Podcast(params)]
    }

    def save() {
        def podcastInstance = new Podcast(params)
        if (!podcastInstance.save(flush: true)) {
            render(view: "create", model: [podcastInstance: podcastInstance])
            return
        }

        flash.message = message(code: 'default.created.message', args: [message(code: 'podcast.label', default: 'Podcast'), podcastInstance.id])
        redirect(action: "show", id: podcastInstance.id)
    }

    def show(Long id) {
        def podcastInstance = Podcast.get(id)
        if (!podcastInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'podcast.label', default: 'Podcast'), id])
            redirect(action: "list")
            return
        }

        [podcastInstance: podcastInstance]
    }

    def edit(Long id) {
        def podcastInstance = Podcast.get(id)
        if (!podcastInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'podcast.label', default: 'Podcast'), id])
            redirect(action: "list")
            return
        }

        [podcast: podcastInstance]
    }

    def update(Long id, Long version) {
        def podcastInstance = Podcast.get(id)
        if (!podcastInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'podcast.label', default: 'Podcast'), id])
            redirect(action: "list")
            return
        }

        if (version != null) {
            if (podcastInstance.version > version) {
                podcastInstance.errors.rejectValue("version", "default.optimistic.locking.failure",
                          [message(code: 'podcast.label', default: 'Podcast')] as Object[],
                          "Another user has updated this Podcast while you were editing")
                render(view: "edit", model: [podcastInstance: podcastInstance])
                return
            }
        }

        podcastInstance.properties = params

        if (!podcastInstance.save(flush: true)) {
            render(view: "edit", model: [podcastInstance: podcastInstance])
            return
        }

        flash.message = message(code: 'default.updated.message', args: [message(code: 'podcast.label', default: 'Podcast'), podcastInstance.id])
        redirect(controller: "configuration", action: "index", id: podcastInstance.id)
    }

    def delete(Long id) {
        def podcastInstance = Podcast.get(id)
        if (!podcastInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'podcast.label', default: 'Podcast'), id])
            redirect(controller: "configuration", action: "index")
            return
        }

        try {
            podcastInstance.delete(flush: true)
            flash.message = message(code: 'default.deleted.message', args: [message(code: 'podcast.label', default: 'Podcast'), id])
            redirect(controller: "configuration", action: "index")
        }
        catch (DataIntegrityViolationException e) {
            flash.message = message(code: 'default.not.deleted.message', args: [message(code: 'podcast.label', default: 'Podcast'), id])
            redirect(controller: "configuration", action: "index")
        }
    }
}

grails-app/views/podcast/_form.gsp
<%@ page import="com.jpcf.backend.domain.Podcast" %>

<div class="fieldcontain ${hasErrors(bean: podcast, field: 'name', 'error')} ">
	<label for="name">
		<g:message code="podcast.name.label" default="Name" />
		
	</label>
	<g:textField name="name" value="${podcast?.name}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: podcast, field: 'description', 'error')} ">
	<label for="description">
		<g:message code="podcast.description.label" default="Description" />
		
	</label>
	<g:textField name="description" value="${podcast?.description}"/>
</div>

grails-app/views/podcast/_inlineForm.gsp
 <g:form controller="fileUpload" action="uploadPodcast" method="post" enctype="multipart/form-data">
 <tr class="tr-input">
   <td><g:textField name="name" /></td>
   <td><g:textField name="description" /></td>
   <td><input type="file" id="fileUpload" name="podcastUpload" /></td>
   <td></td>
   <td><g:actionSubmit class="upload" value="Upload Podcast" action="uploadPodcast" /></td>
 </tr>
 </g:form>

grails-app/views/podcast/_podcast.gsp
 <tr>
   <td>${podcast.name}</td>
   <td>${podcast.description}</td>
   <td><g:formatDate format="MM/dd/yyyy hh:mm a" date="${podcast.dateCreated}" /></td>
   <td></td>
   <td><g:link controller="podcast" action="edit" id="${podcast.id}"><button>Edit</button></g:link><g:link controller="podcast" action="delete" id="${podcast.id}"><button>Delete</button></g:link></td>
 </tr>

grails-app/views/podcast/edit.gsp
<%@ page import="com.jpcf.backend.domain.Podcast" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<div class="nav" role="navigation">
		</div>
		<div id="edit-event" class="content scaffold-edit" role="main">
			<h1>Enter Podcast Details</h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>

			<g:form method="post" >
				<g:hiddenField name="id" value="${podcast?.id}" />
				<g:hiddenField name="version" value="${podcast?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>