grails-app/domain/com/jpcf/backend/domain/Event.groovy
package com.jpcf.backend.domain

class Event {
    String name
    String description
    Date startDate
    Date endDate
	
	String htmlData
    
    static constraints = {
		htmlData nullable: true, maxSize: 10000
    }
    
    static mapping = { sort "startDate" }
}

grails-app/controllers/com/jpcf/backend/domain/EventController.groovy
package com.jpcf.backend.domain

import org.springframework.dao.DataIntegrityViolationException
import grails.converters.JSON
import java.text.ParseException
import java.text.SimpleDateFormat

class EventController {

    static allowedMethods = [save: "POST", update: "POST"]

    def index() {
        redirect(action: "list")
    }

    def create() {
        [eventInstance: new Event(params)]
    }

    def save() {
		SimpleDateFormat formatter = new SimpleDateFormat("M/d/yyyy h:m a")
		def startDate
		def endDate
		
		try {
			startDate = formatter.parse(params.startDate)
			endDate = formatter.parse(params.endDate)
		} catch (ParseException e) {
			flash.message = "Start and end date must be in format MM/dd/yyyy H:m(pm|am)!"
			redirect(controller: "configuration", action: "index")
			return
		}
		
		if (!startDate || !endDate) {
			flash.message = "Start and end date must be in format MM/dd/yyyy H:m(pm|am)!"
			redirect(controller: "configuration", action: "index")
			return
		}
		
		params.startDate = startDate
		params.endDate = endDate
		
        def eventInstance = new Event(params)
        if (!eventInstance.save(flush: true)) {
            flash.message = "Unable to save edit!"
            redirect(controller: "configuration", action: "index")    
            return
        }

        flash.message = message(code: 'default.created.message', args: [message(code: 'event.label', default: 'Event'), eventInstance.id])
        redirect(controller: "configuration", action: "index")
    }

    def show(Long id) {
        def eventInstance = Event.get(id)
        if (!eventInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'event.label', default: 'Event'), id])
            redirect(action: "list")
            return
        }

        [eventInstance: eventInstance]
    }

    def edit(Long id) {
        def event = Event.get(id)
        if (!event) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'event.label', default: 'Event'), id])
            redirect(action: "list")
            return
        }

        [event: event]
    }

    def update(Long id, Long version) {
        def eventInstance = Event.get(id)
        if (!eventInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'event.label', default: 'Event'), id])
            redirect(controller: "configuration", action: "index")
            return
        }

        if (version != null) {
            if (eventInstance.version > version) {
                eventInstance.errors.rejectValue("version", "default.optimistic.locking.failure",
                          [message(code: 'event.label', default: 'Event')] as Object[],
                          "Another user has updated this Event while you were editing")
                render(view: "edit", model: [eventInstance: eventInstance])
                return
            }
        }
		
		SimpleDateFormat formatter = new SimpleDateFormat("M/d/yyyy h:m a")
		def startDate
		def endDate
		
		try {
			startDate = formatter.parse(params.startDate)
			endDate = formatter.parse(params.endDate)
		} catch (ParseException e) {
			flash.message = "Start and end date must be in format MM/dd/yyyy H:m(pm|am)!"
			redirect(controller: "configuration", action: "index")
			return
		}
		
		if (!startDate || !endDate) {
			flash.message = "Start and end date must be in format MM/dd/yyyy H:m(pm|am)!"
			redirect(controller: "configuration", action: "index")
			return
		}
		
		params.startDate = startDate
		params.endDate = endDate

        eventInstance.properties = params

        if (!eventInstance.save(flush: true)) {
            render(view: "edit", model: [eventInstance: eventInstance])
            return
        }

        flash.message = message(code: 'default.updated.message', args: [message(code: 'event.label', default: 'Event'), eventInstance.id])
        redirect(controller: "configuration", action: "index")
    }

    def delete(Long id) {
        def eventInstance = Event.get(id)
        if (!eventInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'event.label', default: 'Event'), id])
            redirect(controller: "configuration", action: "index")
            return
        }

        try {
            eventInstance.delete(flush: true)
            flash.message = message(code: 'default.deleted.message', args: [message(code: 'event.label', default: 'Event'), id])
            redirect(controller: "configuration", action: "index")
        }
        catch (DataIntegrityViolationException e) {
            flash.message = message(code: 'default.not.deleted.message', args: [message(code: 'event.label', default: 'Event'), id])
            redirect(controller: "configuration", action: "index")
        }
    }
	
	def getHtml(Long id) {
		def event = Event.get(id)
		
		if (!event) {
			response.setStatus(404)
			return
		}
		
		render event.htmlData
		return
	}
}

grails-app/views/event/_event.gsp
 <tr>
   <td>${event.name}</td>
   <td>${event.description}</td>
   <td><g:formatDate format="MM/dd/yyyy hh:mm a" date="${event.startDate}" /></td>
   <td><g:formatDate format="MM/dd/yyyy hh:mm a" date="${event.endDate}" /></td>
   <td><g:link controller="event" action="edit" id="${event.id}"><button class="jpcf-edit-button" data-eventId="${event.id}">Edit</button></g:link><g:link controller="event" action="delete" id="${event.id}"><button class="jpcf-delete-button">Delete</button></g:link></td>
 </tr>

grails-app/views/event/_form.gsp
 <% def formatter = new java.text.SimpleDateFormat("MM/dd/yyyy hh:mm a") %>
 <table>
 	<thead>
 	  <th>Name</th>
 	  <th>Description</th>
 	  <th>Start Date</th>
 	  <th>End Date</th>
 	</thead>
 	<tbody>
	<tr class="tr-input">
	  <td><g:textField name="name" id="event-name" value="${event?.name}" /></td>
	  <td><g:textField name="description" id="event-desc" value="${event?.description}" /></td>
	  <td><g:textField name="startDate" id="event-start" value="${formatter.format(event?.startDate ?: new Date())}" /></td>
	  <td><g:textField name="endDate" id="event-end" value="${formatter.format(event?.endDate ?: new Date())}" /></td>
	</tr>
	</tbody>
</table>
<g:if test="${event.id}">
	<div class="textwrapper">
		<h3>Optional HTML Data</h3>
		<g:textArea name="htmlData" id="event-data" value="${event?.htmlData}" />
	</div>
</g:if>

grails-app/views/event/_inlineForm.gsp
 <% def formatter = new java.text.SimpleDateFormat("MM/dd/yyyy hh:mm a") %>
 <g:form controller="event" action="save">
 	<tr class="tr-input">
	   <td><g:textField name="name" id="event-name" value="${event?.name}" /></td>
	   <td><g:textField name="description" id="event-desc" value="${event?.description}" /></td>
	   <td><g:textField name="startDate" id="event-start" value="${formatter.format(event?.startDate ?: new Date())}" /></td>
	   <td><g:textField name="endDate" id="event-end" value="${formatter.format(event?.endDate ?: new Date())}" /></td>
	   <td><g:submitButton name="create-event-button" value="Create Event" /></td>
	</tr>
</g:form>

grails-app/views/event/create.gsp
<%@ page import="com.jpcf.backend.domain.Event" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'event.label', default: 'Event')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-event" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-event" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${eventInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${eventInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form action="save" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/event/edit.gsp
<%@ page import="com.jpcf.backend.domain.Event" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'event.label', default: 'Event')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-event" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
			</ul>
		</div>
		<div id="edit-event" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${eventInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${eventInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form method="post" >
				<g:hiddenField name="id" value="${event?.id}" />
				<g:hiddenField name="version" value="${event?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" formnovalidate="" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/event/list.gsp
<%@ page import="com.jpcf.backend.domain.Event" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'event.label', default: 'Event')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-event" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-event" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
				<thead>
					<tr>
					
						<g:sortableColumn property="description" title="${message(code: 'event.description.label', default: 'Description')}" />
					
						<g:sortableColumn property="endDate" title="${message(code: 'event.endDate.label', default: 'End Date')}" />
					
						<g:sortableColumn property="name" title="${message(code: 'event.name.label', default: 'Name')}" />
					
						<g:sortableColumn property="startDate" title="${message(code: 'event.startDate.label', default: 'Start Date')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${eventInstanceList}" status="i" var="eventInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${eventInstance.id}">${fieldValue(bean: eventInstance, field: "description")}</g:link></td>
					
						<td><g:formatDate date="${eventInstance.endDate}" /></td>
					
						<td>${fieldValue(bean: eventInstance, field: "name")}</td>
					
						<td><g:formatDate date="${eventInstance.startDate}" /></td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${eventInstanceTotal}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/event/show.gsp
<%@ page import="com.jpcf.backend.domain.Event" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'event.label', default: 'Event')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-event" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-event" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list event">
			
				<g:if test="${eventInstance?.description}">
				<li class="fieldcontain">
					<span id="description-label" class="property-label"><g:message code="event.description.label" default="Description" /></span>
					
						<span class="property-value" aria-labelledby="description-label"><g:fieldValue bean="${eventInstance}" field="description"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${eventInstance?.endDate}">
				<li class="fieldcontain">
					<span id="endDate-label" class="property-label"><g:message code="event.endDate.label" default="End Date" /></span>
					
						<span class="property-value" aria-labelledby="endDate-label"><g:formatDate date="${eventInstance?.endDate}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${eventInstance?.name}">
				<li class="fieldcontain">
					<span id="name-label" class="property-label"><g:message code="event.name.label" default="Name" /></span>
					
						<span class="property-value" aria-labelledby="name-label"><g:fieldValue bean="${eventInstance}" field="name"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${eventInstance?.startDate}">
				<li class="fieldcontain">
					<span id="startDate-label" class="property-label"><g:message code="event.startDate.label" default="Start Date" /></span>
					
						<span class="property-value" aria-labelledby="startDate-label"><g:formatDate date="${eventInstance?.startDate}" /></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form>
				<fieldset class="buttons">
					<g:hiddenField name="id" value="${eventInstance?.id}" />
					<g:link class="edit" action="edit" id="${eventInstance?.id}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>